### ISSUE TITLE
RuntimeError: dictionary changed size during iteration (Traceback @ #pyconfr2014 )

### ISSUE THREAD

**Issue by arthurlogilab** [jonathanslenders/ptpython#1]
When typing tab for completion after "import os." I get. This might be a jedi bug but am posting it here first. 

```
In [3]: import os.Exception in thread Thread-49:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/prompt_toolkit/eventloop/base.py", 
    callback()
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/prompt_toolkit/__init__.py", line 3
    completions = list(line.completer.get_completions(document))
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/prompt_toolkit/contrib/python_input
    completions = script.completions()
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 157, in
    completions = get_completions(user_stmt, b)
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 136, in
    return self._simple_complete(path, like)
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 648, in
    return super(Interpreter, self)._simple_complete(path, like)
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 228, in
    names = s.get_defined_names(on_import_stmt=True)
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 94,
    for scope in self.follow():
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 171
    module, rest = self._importer.follow_file_system()
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, i
    rv = function(obj, *args, **kwargs)
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 365
    module, rest = self._follow_sys_path(sys_path_mod)
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 469
    return _load_module(path, source, sys_path=sys_path), rest
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 527
    return load(source) if cached is None else cached.module
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 523
    cache.save_parser(path, name, p)
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/jedi/cache.py", line 241, in save_p
    ParserPickling.save_parser(n, item)
  File "/home/arthur/.virtualenvs/ptpython/local/lib/python2.7/site-packages/jedi/cache.py", line 302, in save_p
    pickle.dump(parser_cache_item, f, pickle.HIGHEST_PROTOCOL)
RuntimeError: dictionary changed size during iteration

```

**Comment by jonathanslenders** [comment]
We are now using a newer version of Jedi and handling about everything that went wrong.
Let's close this ticket until it happens again. Thanks @arthurlogilab for reporting.
