### ISSUE TITLE
AttributeError: 'PythonRepl' object has no attribute 'cli' on ptpython start

### ISSUE THREAD

**Issue by chmielsen** [jonathanslenders/ptpython#103]
I'm trying to run ptpython, but this happens:
```
$ ptpython
>>>
Traceback (most recent call last):
  File "/usr/local/bin/ptpython", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/ptpython/entry_points/run_ptpython.py", line 71, in run
    title='Python REPL (ptpython)')
  File "/usr/local/lib/python2.7/site-packages/ptpython/repl.py", line 307, in embed
    cli.run()
  File "/Library/Python/2.7/site-packages/prompt_toolkit/interface.py", line 358, in run
    self.application.on_start.fire(self)
  File "/Library/Python/2.7/site-packages/prompt_toolkit/utils.py", line 52, in fire
    handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ptpython/repl.py", line 64, in _on_start
    output = self.cli.output
AttributeError: 'PythonRepl' object has no attribute 'cli'  
```
Version info:
```
$ pip show ptpython
---
Metadata-Version: 2.0
Name: ptpython
Version: 0.31
Summary: Python REPL build on top of prompt_toolkit
Home-page: https://github.com/jonathanslenders/ptpython
Author: Jonathan Slenders
Author-email: UNKNOWN
Installer: pip
License: UNKNOWN
Location: /usr/local/lib/python2.7/site-packages
Requires: jedi, docopt, pygments, prompt-toolkit
Classifiers:
Entry-points:
  [console_scripts]
  ptipython = ptpython.entry_points.run_ptipython:run
  ptpython = ptpython.entry_points.run_ptpython:run
```

System info:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1605
```
Any ideas how can I solve this?

**Comment by chmielsen** [comment]
That's a bit embarassing, I had a warning when opening normal python:
```
Could not open PYTHONSTARTUP
IOError: [Errno 2] No such file or directory: '/Users/chmielsen/.pythonrc'
```
After creation of `/Users/chmielsen/.pythonrc`, ptpython starts normally. Closing the issue.

**Comment by ryneeverett** [comment]
I still wonder if this might be a bug as it doesn't seem like `PythonRepl.cli` is defined anywhere.

**Comment by chmielsen** [comment]
My guess is that the one created in repl.py#294:
    cli = PythonCommandLineInterface(python_input=repl, eventloop=eventloop)
was not well defined after:
```
284     repl = PythonRepl(get_globals, get_locals, vi_mode=vi_mode,
285                       history_filename=history_filename,
286                       startup_paths=startup_paths)
```
Maybe because the globals were not set properly. There is definitely some room for improvement on the error message and checkout of parameters on start :)

**Comment by jonathanslenders** [comment]
This was definitely a bug: https://github.com/jonathanslenders/ptpython/commit/de080f84d4ea03f1d1a362737554e53a145ce33a

Thanks for noticing!
