### ISSUE TITLE
importError by Tensorflow

### ISSUE THREAD

**Issue by romanegloo** [jonathanslenders/ptpython#133]
I am not sure if this is a bug, or I didn't configured ptpython correctly.

When I try to import tensorflow, it complains like below:

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jiho/pyenv/tf/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/jiho/pyenv/tf/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 58, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/jiho/pyenv/tf/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/jiho/pyenv/tf/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
Traceback (most recent call last):
  File "/home/jiho/pyenv/tf/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/jiho/pyenv/tf/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
`

Standard python interpreter works fine on importing tensorflow. Let me know if you need more information other than the error message above. Thanks for your supports.

**Comment by jonathanslenders** [comment]
Hi @romanegloo,
Are you using virtualenv? If so, is ptpython installed inside the virtualenv? If not, it is possible that it will look in the global site-packages, rather than in the current virtualenv. (It will always use the packages that have been installed for the Python interpreter that was used to install ptpython.)

Otherwise, try: ``python -m ptpython``.

**Comment by romanegloo** [comment]
Yes, it was installed outside the virtualenv. I've reinstalled ptpython in a virtualenv and it works fine. `python -m ptpython` worked fine as well. Thanks a lot.
