### ISSUE TITLE
AttributeError: 'Lambda' object has no attribute 'get_subscope_by_name' when signature is shown

### ISSUE THREAD

**Issue by ShadowKyogre** [jonathanslenders/ptpython#136]
# Details
ptpython version: 0.35
tested with module: lxml

# Steps to reproduce

* Launch ptpython with a clean configuration
* Turn on showing signatures
* Type the following into the shell:
~~~~python
from lxml.html import builder as E
E.HTML(
       # ignore this line, as the comment here is just meant to indicate where to tab
~~~~

# Expected result

No crash.

# Actual Result
~~~~
>>> from lxml.html import builder as E

>>> E.HTML(                                                                                                       
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/cache.py", line 32, in get
    return self._data[key]
KeyError: 51

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ptpython", line 9, in <module>
    load_entry_point('ptpython==0.35', 'console_scripts', 'ptpython')()
  File "/usr/lib/python3.5/site-packages/ptpython/entry_points/run_ptpython.py", line 71, in run
    title='Python REPL (ptpython)')
  File "/usr/lib/python3.5/site-packages/ptpython/repl.py", line 315, in embed
    cli.run()
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 389, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 154, in run
    t()
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 326, in redraw
    self._redraw()
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 346, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/renderer.py", line 429, in render
    extended_height=size.rows,
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 157, in write_to_screen
    c.write_to_screen(cli, screen, mouse_handlers, WritePosition(xpos, ypos, width, s))
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 348, in write_to_screen
    c.write_to_screen(cli, screen, mouse_handlers, WritePosition(xpos, ypos, s, height))
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 157, in write_to_screen
    c.write_to_screen(cli, screen, mouse_handlers, WritePosition(xpos, ypos, width, s))
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 428, in write_to_screen
    width = fl.content.preferred_width(cli, write_position.width).preferred
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 1644, in preferred_width
    return self.content.preferred_width(cli, max_available_width)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 980, in preferred_width
    cli, max_available_width - total_margin_width)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 249, in preferred_width
    text = token_list_to_text(self._get_tokens_cached(cli))
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 239, in _get_tokens_cached
    cli.render_counter, lambda: self.get_tokens(cli))
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/cache.py", line 35, in get
    value = getter_func()
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 239, in <lambda>
    cli.render_counter, lambda: self.get_tokens(cli))
  File "/usr/lib/python3.5/site-packages/ptpython/layout.py", line 211, in get_tokens
    for i, p in enumerate(sig.params):
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 348, in params
    sub = followed.get_subscope_by_name('__init__')
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 563, in __getattr__
    return getattr(self.base_func, name)
AttributeError: 'Lambda' object has no attribute 'get_subscope_by_name'
~~~~

**Comment by jonathanslenders** [comment]
Hi @ShadowKyogre,

Sorry for replying this late. I fixed it in this commit and released a new ptpython version. (It's a bug in Jedi.) https://github.com/jonathanslenders/ptpython/commit/0efdd87a466f091abafc9998232a33cd76b1e290

Please let me know if you experience any further issues!
Jonathan
