### ISSUE TITLE
previous .ptpython symlink breaks initial startup

### ISSUE THREAD

**Issue by bordeltabernacle** [jonathanslenders/ptpython#141]
On my Windows 7 machine I have a symlink to a previous ptpython configuration.

`~/.ptpython` points to `~/dotfiles/.ptpython`

I uninstalled ptpython via pip and then reinstalled it. On first startup I got this error:

```
> ptpython
Traceback (most recent call last):
  File "c:\users\robertph\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\robertph\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\robertph\AppData\Local\Programs\Python\Python35-32\Scripts\ptpython.exe\__main__.py", line 9, in <module>
  File "c:\users\robertph\appdata\local\programs\python\python35-32\lib\site-packages\ptpython\entry_points\run_ptpython.py", line 36, in run
    os.mkdir(config_dir)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\robertph/.ptpython/'
```

When I deleted the symlink, ptpython loaded up fine.

This appears to be Windows specific, when I recreate this on my Linux machine the existing symlink is respected and doesn't cause any problems.

I'd be interested in opening a PR to fix this, [here](https://github.com/jonathanslenders/ptpython/blob/master/ptpython/entry_points/run_ptpython.py#L32-L36), I just wanted to check my assumptions were ok with you before I opened the PR. 
I was thinking of changing:

```
config_dir = os.path.expanduser(a['--config-dir'] or '~/.ptpython/')

if not os.path.isdir(config_dir):
        os.mkdir(config_dir)
```

to

```
config_dir = os.path.expanduser(a['--config-dir'] or os.path.join('~', '.ptpython'))

if not os.path.isdir(config_dir) or not os.path.islink(config_dir):
        os.mkdir(config_dir)
```

Let me know what you think.

**Comment by bordeltabernacle** [comment]
Interestingly it seems to be a Windows/Cygwin issue.

If the symlink is created in Windows, on `cmd.exe`:
```
C:\Users\robertph>mklink /D .ptpython dotfiles\.ptpython
symbolic link created for .ptpython <<===>> dotfiles\.ptpython
```
then it appears as a directory to Python in both windows Powershell and zsh in Cygwin.
```
>>> os.path.isdir(os.path.join(os.getcwd(), '.ptpython'))
True
```
Whereas if the symlink is created in zsh under Cygwin:
```
ln -sn ~/dotfiles/.ptpython ~/.ptpython
```
It is only recognised as a directory in Cygwin and not in Powershell in Windows...
```
>>> os.path.isdir(os.path.join(os.getcwd(), '.ptpython'))
False
```
