### ISSUE TITLE
Crashes if an invalid \x escape is entered 

### ISSUE THREAD

**Issue by xsleonard** [jonathanslenders/ptpython#154]
If an invalid `\x` escape char is entered into the repl, e.g. `'\x'`, `'\x9'`, `'\xZZ'` (must be a valid hex code), crashes with the following error:

```~» ptpython
>>> '\x9'                                                                                                
Traceback (most recent call last):
  File "/usr/local/bin/ptpython", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/ptpython/entry_points/run_ptpython.py", line 71, in run
    title='Python REPL (ptpython)')
  File "/usr/local/lib/python2.7/site-packages/ptpython/repl.py", line 309, in embed
    cli.run()
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 388, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/eventloop/posix.py", line 154, in run
    t()
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/eventloop/posix.py", line 82, in read_from_stdin
    inputstream.feed(data)
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/terminal/vt100_input.py", line 376, in feed
    self._input_parser.send(c)
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/terminal/vt100_input.py", line 295, in _input_parser_generator
    self._call_handler(match, prefix)
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/terminal/vt100_input.py", line 328, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 947, in feed_key
    cli.input_processor.process_keys()
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/key_binding/input_processor.py", line 201, in process_keys
    self._process_coroutine.send(key_press)
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/key_binding/input_processor.py", line 158, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/key_binding/input_processor.py", line 228, in _call_handler
    handler.call(event)
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/key_binding/registry.py", line 31, in call
    return self.handler(event)
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/key_binding/bindings/basic.py", line 159, in _
    buff.accept_action.validate_and_handle(event.cli, buff)
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/buffer.py", line 81, in validate_and_handle
    if buffer.validate():
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/buffer.py", line 976, in validate
    self.validator.validate(self.document)
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/validation.py", line 64, in validate
    self.validator.validate(document)
  File "/usr/local/lib/python2.7/site-packages/ptpython/validator.py", line 35, in validate
    compile(document.text, '<input>', 'exec', flags=flags, dont_inherit=True)
ValueError: invalid \x escape
```

There doesn't seem to be a way to get the version, e.g. `ptpython -V`, but I'm using whatever is in homebrew.

**Comment by jonathanslenders** [comment]
Hi @xsleonard, thank you very much for pointing this out. This was a bug indeed.
Fixed in: https://github.com/jonathanslenders/ptpython/commit/45c37bb5b5df5c87c8d937ee1de8d62330df6cca
