### ISSUE TITLE
from ptpython.repl import embed throwing ImportError

### ISSUE THREAD

**Issue by lschumm** [jonathanslenders/ptpython#158]
# The Issue

I was trying out launching PtPython from within Python. I ran

```
from ptpython.repl import embed
```

As the README instructs. However, the following error arose:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/ptpython/repl.py", line 20, in <module>
    from prompt_toolkit.styles import style_from_pygments
ImportError: cannot import name style_from_pigments
```

# Info
- Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
- [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
- MacBook Air (4GB RAM, Core i5), Mid '16, OS X Sierra 10.11, Safari Version 10.0.1 (12602.2.14.0.7), Google Chrome 53.0.2785.89 (64-bit)

**Comment by lschumm** [comment]
Looks like `pip install --upgrade prompt_toolkit` seemed to resolve the issue.
