### ISSUE TITLE
Invalid version

### ISSUE THREAD

**Issue by thisgf** [jonathanslenders/ptpython#171]
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\ptpython.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\ptpython\entry_points\run_ptpython.py", line 71, in run
    title='Python REPL (ptpython)')
  File "c:\python27\lib\site-packages\ptpython\repl.py", line 294, in embed
    startup_paths=startup_paths)
  File "c:\python27\lib\site-packages\ptpython\repl.py", line 51, in __init__
    super(PythonRepl, self).__init__(*a, **kw)
  File "c:\python27\lib\site-packages\ptpython\python_input.py", line 208, in __init__
    self.code_styles = get_all_code_styles()
  File "c:\python27\lib\site-packages\ptpython\style.py", line 19, in get_all_code_styles
    result = dict((name, get_style_by_name(name).styles) for name in get_all_styles())
  File "c:\python27\lib\site-packages\ptpython\style.py", line 19, in <genexpr>
    result = dict((name, get_style_by_name(name).styles) for name in get_all_styles())
  File "c:\python27\lib\site-packages\pygments\styles\__init__.py", line 79, in get_all_styles
    for name, _ in find_plugin_styles():
  File "c:\python27\lib\site-packages\pygments\plugin.py", line 62, in find_plugin_styles
    for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
  File "c:\python27\lib\site-packages\pygments\plugin.py", line 45, in iter_entry_points
    import pkg_resources
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 3030, in <module>
    @_call_aside
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 3014, in _call_aside
    f(*args, **kwargs)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 3043, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 645, in _build_master
    ws = cls()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 638, in __init__
    self.add_entry(entry)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 694, in add_entry
    for dist in find_distributions(entry, True):
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2010, in find_on_path
    path_item_entries = _by_version_descending(os.listdir(path_item))
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1994, in _by_version_descending
    return sorted(names, key=_by_version, reverse=True)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1992, in _by_version
    return [packaging.version.parse(part) for part in parts]
  File "c:\python27\lib\site-packages\packaging\version.py", line 31, in parse
    return Version(version)
  File "c:\python27\lib\site-packages\packaging\version.py", line 202, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

environment:
ptpython: 0.36
os: Windows7
python: 2.7.13 64bit

**Comment by Pagliacii** [comment]
```python
Traceback (most recent call last):
  File "f:\anaconda3\envs\py2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "f:\anaconda3\envs\py2\lib\runpy.py", line 72, in _run_code

    exec code in run_globals
  File "F:\Anaconda3\envs\py2\Scripts\ptpython.exe\__main__.py", line 9, in <module>
  File "f:\anaconda3\envs\py2\lib\site-packages\ptpython\entry_points\run_ptpython.py", line 71, in run
    title='Python REPL (ptpython)')
  File "f:\anaconda3\envs\py2\lib\site-packages\ptpython\repl.py", line 299, in embed
    startup_paths=startup_paths)
  File "f:\anaconda3\envs\py2\lib\site-packages\ptpython\repl.py", line 52, in __init__
    super(PythonRepl, self).__init__(*a, **kw)
  File "f:\anaconda3\envs\py2\lib\site-packages\ptpython\python_input.py", line 209, in __init__
    self.code_styles = get_all_code_styles()
  File "f:\anaconda3\envs\py2\lib\site-packages\ptpython\style.py", line 19, in get_all_code_styles
    result = dict((name, get_style_by_name(name).styles) for name in get_all_styles())
  File "f:\anaconda3\envs\py2\lib\site-packages\ptpython\style.py", line 19, in <genexpr>
    result = dict((name, get_style_by_name(name).styles) for name in get_all_styles())
  File "f:\anaconda3\envs\py2\lib\site-packages\pygments\styles\__init__.py", line 79, in get_all_styles
    for name, _ in find_plugin_styles():
  File "f:\anaconda3\envs\py2\lib\site-packages\pygments\plugin.py", line 62, in find_plugin_styles
    for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
  File "f:\anaconda3\envs\py2\lib\site-packages\pygments\plugin.py", line 45, in iter_entry_points
    import pkg_resources
  File "f:\anaconda3\envs\py2\lib\site-packages\pkg_resources\__init__.py", line 3019, in <module>
    @_call_aside
  File "f:\anaconda3\envs\py2\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "f:\anaconda3\envs\py2\lib\site-packages\pkg_resources\__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "f:\anaconda3\envs\py2\lib\site-packages\pkg_resources\__init__.py", line 646, in _build_master
    ws = cls()
  File "f:\anaconda3\envs\py2\lib\site-packages\pkg_resources\__init__.py", line 639, in __init__
    self.add_entry(entry)
  File "f:\anaconda3\envs\py2\lib\site-packages\pkg_resources\__init__.py", line 695, in add_entry
    for dist in find_distributions(entry, True):
  File "f:\anaconda3\envs\py2\lib\site-packages\pkg_resources\__init__.py", line 2005, in find_on_path
    path_item_entries = _by_version_descending(os.listdir(path_item))
  File "f:\anaconda3\envs\py2\lib\site-packages\pkg_resources\__init__.py", line 1989, in _by_version_descending
    return sorted(names, key=_by_version, reverse=True)
  File "f:\anaconda3\envs\py2\lib\site-packages\pkg_resources\__init__.py", line 1987, in _by_version
    return [packaging.version.parse(part) for part in parts]
  File "f:\anaconda3\envs\py2\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 31, in parse
    return Version(version)
  File "f:\anaconda3\envs\py2\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 202, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))

UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```
I got same error like you.
Environment:
ptpython: 0.39
os: Windows10
python: Anaconda virtual environment Python 2.7.13

**Comment by Pagliacii** [comment]
Ok, I fix up it!
If you install it by pip, you should uninstall it and reinstall it by git!
It works for me!
