### ISSUE TITLE
Multiprocessing issue 'Can't pickle <function ....'

### ISSUE THREAD

**Issue by several27** [jonathanslenders/ptpython#193]
Hey, 
the following code is not working in ptpython on python version 3. 

```python
from multiprocessing.pool import Pool

def do(x):
    return x 

pool = Pool(processes=16,  maxtasksperchild=100)
done_x = []
for x in pool.imap_unordered(do, [1, 2, 3, 4, 5]):
    done_x.append(x)
```

It produces the following error: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 385, in _handle_tasks
    put(task)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function do at 0x10388c268>: attribute lookup do on __main__ failed
Can't pickle <function do at 0x10388c268>: attribute lookup do on __main__ failed
```

I have tested the code on Python 3.5.2 on ubuntu and mac os. It is working correctly in default python's REPL, in jupyter, and by running it directly.

**Comment by jonathanslenders** [comment]
Hi @several27, this looks like a bug.
It's pickle. The following code has the same issue:
```python
def f():
    pass
import pickle
pickle.dumps(f)
```
Thanks for reporting this bug!

**Comment by danai-antoniou** [comment]
@jonathanslenders Any update on this? Also experiencing this bug

**Comment by ttarter3** [comment]
@danai-antoniou I updated Anaconda to the latest version and that fixed the problem for me. Not sure which package was the issue.  I read online it could be multiprocessing, Ipython, or pickle.

**Comment by danai-antoniou** [comment]
@ttarter3 yep, good shout, worked! Somehow conda resolves conflicts and is able to pickle functions, but outside a conda environment, it's not working - quite baffling.

**Comment by PS-ChaseEdwards** [comment]
Running into the same issue here.
