### ISSUE TITLE
Crash when trying to move "nothing" to history pane

### ISSUE THREAD

**Issue by kannes** [jonathanslenders/ptpython#214]
Installed ptpython-0.41-py3-none-any.whl from pip then ran ~/.local/bin/ptpython3 . I entered nothing but hit F3 and then hit Space. ptpython crashed with:

```
  Traceback (most recent call last):                                                           │ 
  File "/home/me/.local/bin/ptpython3", line 11, in <module>                               │ 
    sys.exit(run())                                                                            │ 
  File "/home/me/.local/lib/python3.6/site-packages/ptpython/entry_points/run_ptpython.py", line 74, in run
    title='Python REPL (ptpython)')                                                            │ 
  File "/home/me/.local/lib/python3.6/site-packages/ptpython/repl.py", line 320, in embed  │ 
    cli.run()                                                                                  │ 
  File "/home/me/.local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 415, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())                          │ 
  File "/home/me/.local/lib/python3.6/site-packages/prompt_toolkit/eventloop/posix.py", line 159, in run
    t()                                                                                        │ 
  File "/home/me/.local/lib/python3.6/site-packages/prompt_toolkit/eventloop/posix.py", line 82, in read_from_stdin
    inputstream.feed(data)                                                                     │ 
  File "/home/me/.local/lib/python3.6/site-packages/prompt_toolkit/terminal/vt100_input.py", line 398, in feed
    self._input_parser.send(c)                                                                 │ 
  File "/home/me/.local/lib/python3.6/site-packages/prompt_toolkit/terminal/vt100_input.py", line 325, in _input_parser_generator
    self._call_handler(prefix[0], prefix[0])                                                   │ 
  File "/home/me/.local/lib/python3.6/site-packages/prompt_toolkit/terminal/vt100_input.py", line 340, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))                                         │ 
  File "/home/me/.local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 1048, in feed_key
    cli.input_processor.process_keys()                                                         │ 
  File "/home/me/.local/lib/python3.6/site-packages/prompt_toolkit/key_binding/input_processor.py", line 219, in process_keys
    self._process_coroutine.send(key_press)                                                    │ 
  File "/home/me/.local/lib/python3.6/site-packages/prompt_toolkit/key_binding/input_processor.py", line 176, in _process
    self._call_handler(matches[-1], key_sequence=buffer[:])                                    │ 
  File "/home/me/.local/lib/python3.6/site-packages/prompt_toolkit/key_binding/input_processor.py", line 247, in _call_handler
    handler.call(event)                                                                        │ 
  File "/home/me/.local/lib/python3.6/site-packages/prompt_toolkit/key_binding/registry.py", line 61, in call
    return self.handler(event)                                                                 │ 
  File "/home/me/.local/lib/python3.6/site-packages/ptpython/history_browser.py", line 443, in _
    history_mapping.update_default_buffer(event.cli)                                           │ 
  File "/home/me/.local/lib/python3.6/site-packages/ptpython/history_browser.py", line 399, in update_default_buffer
    self.get_new_document(b.cursor_position), bypass_readonly=True)                            │ 
  File "/home/me/.local/lib/python3.6/site-packages/ptpython/history_browser.py", line 383, in get_new_document
    lines.append(self.history_lines[line_no])                                                  │ 
IndexError: list index out of range                                                            │ 
```

I guess it tried to append something that does not exist yet ;)

**Comment by jonathanslenders** [comment]
This is clearly a bug. Thank you for reporting!
