### ISSUE TITLE
ptpython shows JEDI exception when trying relative imports beyond file system root

### ISSUE THREAD

**Issue by L3viathan** [jonathanslenders/ptpython#219]
I assume this is a JEDI bug, not a ptpython bug, but it should probably not be shown:

When being _n_ directories deep in your file system, typing `from ` and then n+1 dots, ptpython shows the following exception (but continues to be working):

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/local/lib/python3.4/dist-packages/ptpython/completer.py", line 127, in get_completions
    completions = script.completions()
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/__init__.py", line 157, in completions
    completions = completion.completions()
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/completion.py", line 99, in completions
    completion_names = self._get_context_completions()
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/completion.py", line 194, in _get_context_completions
    only_modules=only_modules,
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/completion.py", line 264, in _get_importer_names
    i = imports.Importer(self._evaluator, names, self._module_context, level)
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/imports.py", line 225, in __init__
    _add_error(module_context, import_path[-1])
IndexError: list index out of range
```

To reproduce, open a ptpython REPL, type `from ` and then keep typing dots until you see the exception.

**Comment by facingBackwards** [comment]
I'm not seeing this. What version of ptpython/Jedi are you using?

**Comment by L3viathan** [comment]
I have the latest versions installable via pip on Debian Jessie (i.e. for Python 3.4):

- ptpython 0.41
- jedi 0.11.0
