### ISSUE TITLE
Not work in virtualenv

### ISSUE THREAD

**Issue by ComradeDOS** [jonathanslenders/ptpython#26]
Traceback (most recent call last):
  File "/home/dos/.virtualenvs/accommodirect/bin/ptpython", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/dos/.virtualenvs/accommodirect/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/home/dos/.virtualenvs/accommodirect/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/dos/.virtualenvs/accommodirect/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/dos/.virtualenvs/accommodirect/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: jedi>=0.8.1

pip freeze | grep jedi
jedi==0.8.1-final0

**Comment by RonnyPfannschmidt** [comment]
its a pip bug, update pip
