### ISSUE TITLE
run ptipython in bash give error: No module named terminal.embed

### ISSUE THREAD

**Issue by hackrole** [jonathanslenders/ptpython#33]
I install with
```bash
pip install ptpython
```
the ptpython works ok, but when I try to run ptipython, it give the follow errors.

```bash
Traceback (most recent call last):
  File "/usr/local/bin/ptipython", line 9, in <module>
    load_entry_point('ptpython==0.5', 'console_scripts', 'ptipython')()
  File "/usr/local/lib/python2.7/dist-packages/ptpython/entry_points/run_ptipython.py", line 35, in run
    from ptpython.ipython import embed
  File "/usr/local/lib/python2.7/dist-packages/ptpython/ipython.py", line 25, in <module>
    from IPython.terminal.embed import InteractiveShellEmbed as _InteractiveShellEmbed
ImportError: No module named terminal.embed
```

I have tried to install terminal but it still not work.

**Comment by jonathanslenders** [comment]
I guess you have an older version of IPython. Could you try running:

```
pip install -U IPython
```

**Comment by hackrole** [comment]
yes, it work ok now, thanks.
