### ISSUE TITLE
Strange parsing errors 

### ISSUE THREAD

**Issue by xiaoweiz** [jonathanslenders/ptpython#44]
While typing the following `lambda` expression with two arguments, `lambda a, b: a if a > b else b`, I got a parsing error

It was fine at first
```python
lambda a, b: a 
```
until I typed  "space" and `i`, the error popped up

```python
lambda a, b: a iException in thread Thread-18:
Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/cache.py", line 141r
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '__parser'

During handling of the above exception, another exception occurred:idebar - CPython 3.4.3

Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"s
    clear_names(c.children)
AttributeError: 'Name' object has no attribute 'children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/ptpython/utils.py", linet
    namespaces=[locals, globals])
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/api/__init__.py", l_
    self._parser.module())
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/user_contexte
    return self._parser().module
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/cache.py", line 143r
    result = func(self)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/user_contextr
    parser = Parser(self._grammar, self._source, self._path)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"_
    self.module = p.parse(self._tokenize(tokenizer))
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/pgen2/parse.e
    if self.addtoken(type, value, prefix, start_pos):
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/pgen2/parse.n
    value, start_pos, prefix, self.addtoken)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"y
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"l
    clear_names(children=node[1])
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"s
    clear_names(c.children)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"s
    clear_names(c.children)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"s
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: 'a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/threading.py", line 920, in _bootstrapr
    self.run()
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/prompt_toolkit/interfacen
    CompleteEvent(text_inserted=True)))
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/prompt_toolkit/contrib/rs
    self._get_completions_for_match(m, complete_event))
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/prompt_toolkit/contrib/rs
    for i in items:
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/prompt_toolkit/contrib/rh
    for completion in completer.get_completions(document, complete_event):
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/ptpython/completer.py", s
    script = get_jedi_script_from_document(document, self.get_locals(), self.get_globals()
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/ptpython/utils.py", linet
    except jedi.common.MultiLevelStopIteration:
AttributeError: 'module' object has no attribute 'MultiLevelStopIteration'

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/cache.py", line 141r
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '__parser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"s
    clear_names(c.children)
AttributeError: 'Name' object has no attribute 'children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/ptpython/utils.py", linet
    namespaces=[locals, globals])
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/api/__init__.py", l_
    self._parser.module())
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/user_contexte
    return self._parser().module
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/cache.py", line 143r
    result = func(self)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/user_contextr
    parser = Parser(self._grammar, self._source, self._path)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"_
    self.module = p.parse(self._tokenize(tokenizer))
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/pgen2/parse.e
    if self.addtoken(type, value, prefix, start_pos):
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/pgen2/parse.n
    value, start_pos, prefix, self.addtoken)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"y
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"l
    clear_names(children=node[1])
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"s
    clear_names(c.children)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"s
    clear_names(c.children)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/jedi/parser/__init__.py"s
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: 'a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/threading.py", line 920, in _bootstrapr
    self.run()
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/ptpython/python_input.pyn
    script = get_jedi_script_from_document(document, self.get_locals(), self.get_globals()
  File "/Users/zhangxiaowei/anaconda/lib/python3.4/site-packages/ptpython/utils.py", linet
    except jedi.common.MultiLevelStopIteration:
AttributeError: 'module' object has no attribute 'MultiLevelStopIteration'
```

**Comment by jonathanslenders** [comment]
Hi @xiaoweiz 

Could you tell me which version of Jedi you have? Do ``pip freeze``. I think you have already Jedi 0.9.0 while ptpython still defines Jedi==0.8.1 in the requirements. If that's not the issue, we have to look further.

In any case, I didn't notice that recently we got a nice, new release of Jedi. So, I guess it's time to update the autocompletion library.

Jonathan

**Comment by xiaoweiz** [comment]
It's Jedi 0.9. I guess I run `pip install -U ptpython` at some moment.

**Comment by offero** [comment]
Same thing happened to me. Many MultiLevelStopIteration issues.

**Comment by jonathanslenders** [comment]
Ok, I'll make a priority of this.

**Comment by jonathanslenders** [comment]
This was fixed in: https://github.com/jonathanslenders/ptpython/commit/4589d7bb51fee5ba0cc7058df601fb83d4f80526

I will do a new Pypi release soon.
