### ISSUE TITLE
"ImportError: cannot import name windll" on Mac OS X

### ISSUE THREAD

**Issue by martinpllu** [jonathanslenders/ptpython#60]
When I launch on Mac OS X 10.9.5, Python 2.7.5 I get the error below. I also get the same error in a new virtualenv. 

I guess this might be a prompt_toolkit bug but I thought I'd start here.

Thanks. 

➜  ~  ptpython
Traceback (most recent call last):
  File "/usr/local/bin/ptpython", line 7, in <module>
    from ptpython.entry_points.run_ptpython import run
  File "/Library/Python/2.7/site-packages/ptpython/entry_points/run_ptpython.py", line 25, in <module>
    from ptpython.repl import embed, enable_deprecation_warnings, run_config
  File "/Library/Python/2.7/site-packages/ptpython/repl.py", line 16, in <module>
    from prompt_toolkit.application import AbortAction
  File "/Library/Python/2.7/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/Library/Python/2.7/site-packages/prompt_toolkit/interface.py", line 22, in <module>
    from .input import StdinInput, Input
  File "/Library/Python/2.7/site-packages/prompt_toolkit/input.py", line 14, in <module>
    from .terminal.win32_input import raw_mode, cooked_mode
  File "/Library/Python/2.7/site-packages/prompt_toolkit/terminal/win32_input.py", line 1, in <module>
    from ctypes import windll, pointer
ImportError: cannot import name windll

**Comment by jonathanslenders** [comment]
Hi @martinpllu,

Thanks a lot for reporting, I appreciate it!

It's fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/aa32f27944c9cd4e370d7e993bb7649a1ad66348

A new release was pushed to Pypi. Can you try again?

Jonathan

**Comment by martinpllu** [comment]
Hi Jonathan,

Working now. 

Thanks for fixing this so quickly, and congratulations on a very cool project.

Cheers,

Martin
