### ISSUE TITLE
Exception in jedi crashes ptpython(another one)

### ISSUE THREAD

**Issue by zhoushun123** [jonathanslenders/ptpython#71]
The following crashes ptpython, it exists  immediately after entering the '0' sign.
My python Env:
Windows7 x64 with SP1
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
docopt (0.6.2)
ipython (4.0.0)
ipython-genutils (0.1.0)
jedi (0.9.0)
prompt-toolkit (0.50)
ptpython (0.22)

```python
In [1]:   1 def frange(start, stop, increment):
          2     x = start
          3     while x < stop:
          4         yield x
          5         x += increment

In [2]: for n in frange(0Exception in thread Thread-176:
Traceback (most recent call last):
  File "d:\python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "d:\python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "d:\python27\lib\site-packages\prompt_toolkit\interface.py", line 612, in
 run
    CompleteEvent(text_inserted=True)))
  File "d:\python27\lib\site-packages\prompt_toolkit\contrib\regular_languages\c
ompletion.py", line 37, in get_completions
    self._get_completions_for_match(m, complete_event))
  File "d:\python27\lib\site-packages\prompt_toolkit\contrib\regular_languages\c
ompletion.py", line 81, in _remove_duplicates
    for i in items:
  File "d:\python27\lib\site-packages\prompt_toolkit\contrib\regular_languages\c
ompletion.py", line 64, in _get_completions_for_match
    for completion in completer.get_completions(document, complete_event):
  File "d:\python27\lib\site-packages\ptpython\completer.py", line 127, in get_c
ompletions
    completions = script.completions()
  File "d:\python27\lib\site-packages\jedi\api\__init__.py", line 192, in comple
tions
    for call_sig in self.call_signatures():
  File "d:\python27\lib\site-packages\jedi\api\__init__.py", line 521, in call_s
ignatures
    self.source, self._pos)
  File "d:\python27\lib\site-packages\jedi\cache.py", line 93, in wrapper
    value = next(generator)
  File "d:\python27\lib\site-packages\jedi\cache.py", line 115, in cache_call_si
gnatures
    yield evaluator.eval_element(call)
  File "d:\python27\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapp
er
    rv = function(obj, *args, **kwargs)
  File "d:\python27\lib\site-packages\jedi\evaluate\__init__.py", line 169, in e
val_element
    return self._eval_atom(element)
  File "d:\python27\lib\site-packages\jedi\evaluate\__init__.py", line 230, in _
eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "d:\python27\lib\site-packages\jedi\evaluate\__init__.py", line 120, in f
ind_types
    return f.find(scopes, search_global)
  File "d:\python27\lib\site-packages\jedi\debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "d:\python27\lib\site-packages\jedi\evaluate\finder.py", line 86, in find

    names = self.filter_name(scopes)
  File "d:\python27\lib\site-packages\jedi\evaluate\finder.py", line 177, in fil
ter_name
    names = self.names_dict_lookup(names_dict, position)
  File "d:\python27\lib\site-packages\jedi\evaluate\finder.py", line 125, in nam
es_dict_lookup
    names = filter_definition_names(names, self.name_str, position)
  File "d:\python27\lib\site-packages\jedi\evaluate\finder.py", line 57, in filt
er_definition_names
    stmt = names[0].get_definition()
  File "d:\python27\lib\site-packages\jedi\evaluate\helpers.py", line 159, in ge
t_definition
    return self.parent
  File "d:\python27\lib\site-packages\jedi\cache.py", line 143, in wrapper
    result = func(self)
  File "d:\python27\lib\site-packages\jedi\api\interpreter.py", line 81, in pare
nt
    with open(path) as f:
IOError: [Errno 2] No such file or directory: 'D:\\Python27\\Scripts\\ptipython.
exe\\__main__.py'
```

**Comment by jonathanslenders** [comment]
Hi @zhoushun123 
Thanks for reporting!
This has been fixed now: https://github.com/jonathanslenders/ptpython/commit/0fa994e6c555091ebd781d478fad189edb61bde8
