### ISSUE TITLE
Scripts started with -i cannot take args 

### ISSUE THREAD

**Issue by endrebak** [jonathanslenders/ptpython#80]
The following works with ipython:

```
ipython -i pls_on_trunk_regions.py -- ../from_epic_mergepools_to_trunk_regions/data/regions.csv
```

In ptipython however, it does not; the csv-file is read as a python-file, not an argument to the script in the python file.

```
Traceback (most recent call last):
  File "/Users/labsenter/anaconda/bin/ptipython", line 11, in <module>
    sys.exit(run())
  File "/Users/labsenter/anaconda/lib/python2.7/site-packages/ptpython/entry_points/run_ptipython.py", line 51, in run
    six.exec_(compile(open(a['<file>'], "rb").read(), a['<file>'], 'exec'))
  File "../from_epic_mergepools_to_trunk_regions/data/regions.csv", line 1
    Trunk	Chromosome	Start	End	Island_nb	Monotonic	Islands	Type	Exp2_0h_H3K27me3.bed.gz	Exp1_0h_H3K27me3.bed.gz	Exp2_0h_Input.bed.gz	Exp1_0h_Input.bed.gz	Exp1_12h_H3K27me3.bed.gz	Exp2_12h_H3K27me3.bed.gz	Exp1_12h_Input.bed.gz	Exp2_12h_Input.bed.gz	Exp2_15h_H3K27me3.bed.gz	Exp1_15h_H3K27me3.bed.gz	Exp2_15h_Input.bed.gz	Exp1_15h_Input.bed.gz	Exp2_18h_H3K27me3.bed.gz	Exp1_18h_H3K27me3.bed.gz	Exp1_18h_Input.bed.gz	Exp2_18h_Input.bed.gz	Exp1_21h_H3K27me3.bed.gz	Exp2_21h_H3K27me3.bed.gz	Exp1_21h_Input.bed.gz	Exp2_21h_Input.bed.gz	Exp1_24h_H3K27me3.bed.gz	Exp2_24h_H3K27me3.bed.gz	Exp2_24h_Input.bed.gz	Exp1_24h_Input.bed.gz	Exp1_3h_H3K27me3.bed.gz	Exp2_3h_H3K27me3.bed.gz	Exp2_3h_Input.bed.gz	Exp1_3h_Input.bed.gz	Exp1_6h_H3K27me3.bed.gz	Exp2_6h_H3K27me3.bed.gz	Exp1_6h_Input.bed.gz	Exp2_6h_Input.bed.gz	Exp2_9h_H3K27me3.bed.gz	Exp1_9h_H3K27me3.bed.gz	Exp2_9h_Input.bed.gz	Exp1_9h_Input.bed.gz
                   ^
SyntaxError: invalid syntax
```

**Comment by jonathanslenders** [comment]
Hi @endrebak,

Thanks for reporting this!
It should be fixed in this commit: https://github.com/jonathanslenders/ptpython/commit/02add6af472e47e21404aa6cce50e15c5f50e19e

Jonathan

**Comment by endrebak** [comment]
Neat, thanks.
